# Generated by Django 3.1.1 on 2021-03-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('dept_name', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('dept_code', models.CharField(max_length=2)),
                ('dept_core', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Departments',
            },
        ),
    ]
