# Generated by Django 3.1.1 on 2021-03-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('roll_no', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('stud_name', models.CharField(max_length=25)),
                ('mail_id', models.EmailField(max_length=254)),
                ('dept_name', models.CharField(max_length=15)),
                ('hostel', models.CharField(max_length=12)),
                ('room_no', models.CharField(max_length=6)),
            ],
            options={
                'verbose_name_plural': 'Students',
            },
        ),
    ]
