# Generated by Django 3.1.1 on 2021-02-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.CharField(default='MNC', max_length=3),
        ),
    ]
