# Generated by Django 3.1.1 on 2021-02-17 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_auto_20210217_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='branch',
            new_name='Branch',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='hostel',
            new_name='Hostel',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='mail',
            new_name='Mail',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='roll_no',
            new_name='Roll_No',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='room_no',
            new_name='Room_No',
        ),
    ]
