# Generated by Django 3.1.1 on 2021-03-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_course_prerequisites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='prerequisites',
            field=models.CharField(max_length=10),
        ),
    ]
