# Generated by Django 3.1.1 on 2021-03-07 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_auto_20210307_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('slot', models.CharField(max_length=2, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Slot',
            },
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.slot')),
            ],
            options={
                'verbose_name_plural': 'Timetable',
            },
        ),
    ]
