# Generated by Django 3.1.1 on 2021-03-11 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_auto_20210307_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.course')),
                ('roll_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.student')),
            ],
            options={
                'verbose_name_plural': 'Registered Courses',
            },
        ),
    ]
