# Generated by Django 3.1.1 on 2021-03-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_registeredcourses'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_credits',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='course',
            name='references',
            field=models.CharField(default='asdad', max_length=300),
        ),
    ]
