# Generated by Django 3.1.1 on 2021-03-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0011_auto_20210313_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_credits',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='references',
            field=models.CharField(max_length=300),
        ),
    ]
