# Generated by Django 3.1.1 on 2021-03-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0012_auto_20210313_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='references',
            field=models.TextField(max_length=300),
        ),
    ]
