# Generated by Django 3.1.1 on 2021-03-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0013_auto_20210313_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='references',
            field=models.TextField(max_length=500),
        ),
    ]
