# Generated by Django 3.1.1 on 2021-03-13 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0014_auto_20210313_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='attendance',
        ),
    ]
