# Generated by Django 3.1.1 on 2021-03-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0015_remove_course_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredcourses',
            name='attendance',
            field=models.IntegerField(default=90),
        ),
    ]
