# Generated by Django 3.1.1 on 2021-04-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0017_auto_20210313_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='compulsary',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.IntegerField(default=8),
        ),
    ]
