# Generated by Django 3.1.1 on 2021-04-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0018_auto_20210404_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='compulsary',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.IntegerField(),
        ),
    ]
