# Generated by Django 3.1.1 on 2021-04-04 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0019_auto_20210404_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='dept_name',
            field=models.ForeignKey(default='MATHS', on_delete=django.db.models.deletion.CASCADE, to='chatbot.department'),
        ),
    ]
