# Generated by Django 3.1.1 on 2021-04-04 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0022_auto_20210404_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationdetails',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.department'),
        ),
    ]
