# Generated by Django 3.1.1 on 2021-04-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0023_auto_20210404_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='elective',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='course',
            name='lab',
            field=models.BooleanField(default=1),
        ),
    ]
