# Generated by Django 3.1.1 on 2021-04-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0024_auto_20210404_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='elective',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='lab',
            field=models.BooleanField(),
        ),
    ]
